server:
  servlet:
    session:
      cookie:
        name: PHPSESSIONID
      timeout: 600
  port: 8081
spring:
  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        query:
          conventional_java_constants: false
  profiles:
    active: dev
  freemarker:
    enabled: true
    cache: true
    suffix: .ftl
okta:
  oauth2:
    client-id: 0oac471c2iq43VmXV356
    issuer: https://dev-189678.okta.com/oauth2/default